export const lightData = {
  street: 'Вул. Князя Романа Мстиславича',
  houseNumber: '4',
  queueNumber: 'Черга 4.1',
  lastUpdate: '26.11.2025 01:48',
  today: ['00:00 - 06:00', '10:00 - 16:30', '20:30 - 24:00'],
  todayDate: '26.11.25',
  tomorrow: ['1'],
  tomorrowDate: '27.11.25',
  weekSchedule: {
    schedule: [
      {
        dayName: 'Понеділок',
        dayNameEn: 'Monday',
        isToday: false,
        isYesterday: false,
        hours: [
          'on',
          'off-second-half',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off-first-half',
          'on',
          'on',
          'on',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off',
          'on',
          'on',
          'on',
          'off-second-half',
          'off',
        ],
      },
      {
        dayName: 'Вівторок',
        dayNameEn: 'Tuesday',
        isToday: false,
        isYesterday: true,
        hours: [
          'off',
          'off',
          'off',
          'off',
          'off',
          'off-first-half',
          'on',
          'on',
          'on',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off',
          'on',
          'on',
          'on',
          'off-second-half',
          'off',
          'off',
          'off',
          'off',
        ],
      },
      {
        dayName: 'Середа',
        dayNameEn: 'Wednesday',
        isToday: true,
        isYesterday: false,
        hours: [
          'on',
          'on',
          'on',
          'on',
          'on',
          'on',
          'off',
          'off',
          'off',
          'off',
          'on',
          'on',
          'on',
          'on',
          'on',
          'on',
          'off-second-half',
          'off',
          'off',
          'off',
          'off-first-half',
          'on',
          'on',
          'on',
        ],
      },
      {
        dayName: 'Четвер',
        dayNameEn: 'Thursday',
        isToday: false,
        isYesterday: false,
        hours: [
          'on',
          'on',
          'on',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off',
          'on',
          'on',
          'on',
          'off-second-half',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off-first-half',
          'on',
          'on',
          'on',
        ],
      },
      {
        dayName: "П'ятниця",
        dayNameEn: 'Friday',
        isToday: false,
        isYesterday: false,
        hours: [
          'off',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off',
          'on',
          'on',
          'on',
          'off-second-half',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off-first-half',
          'on',
          'on',
          'on',
          'off',
          'off',
          'off',
        ],
      },
      {
        dayName: 'Субота',
        dayNameEn: 'Saturday',
        isToday: false,
        isYesterday: false,
        hours: [
          'off',
          'off',
          'off',
          'off',
          'on',
          'on',
          'on',
          'off-second-half',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off-first-half',
          'on',
          'on',
          'on',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off',
        ],
      },
      {
        dayName: 'Неділя',
        dayNameEn: 'Sunday',
        isToday: false,
        isYesterday: false,
        hours: [
          'off',
          'on',
          'on',
          'on',
          'off-second-half',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off-first-half',
          'on',
          'on',
          'on',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off',
          'off',
          'on',
          'on',
        ],
      },
    ],
    timestamp: 1764149703118,
  },
};
